def get_prompt(theme: str) -> str:
    base = (
        """Create a soft, subtle 3D animated looping background video designed for a casual Bingo game UI.\n"
        "This background must appeal to a mature casual-gaming audience (ages 40–45), so avoid intense\n"
        "motion, fast effects, or overly bright colors. Keep everything calm, warm, and comfortable.\n\n"
        "--- THEME ---\n"
        "Apply the user-given theme: {THEME}\n"
        "Interpret it softly and tastefully in a cozy, friendly, whimsical mobile-game art style.\n\n"
        "--- LOOPING REQUIREMENT (CRITICAL) ---\n"
        "The first frame and last frame must be *identical* for a perfect infinite loop.\n"
        "Use a cyclic camera motion such as a slight circular pan or gentle sway that returns\n"
        "exactly to its starting position. No linear drifting, no perspective changes that\n"
        "cannot loop cleanly.\n\n"
        "--- MOTION REQUIREMENTS (VERY SUBTLE) ---\n"
        "• Only minimal motion: gentle cloud drift, faint shimmer, soft particles, or slow ambient lighting.\n"
        "• Avoid busy animation; keep motion almost unnoticeable but alive.\n"
        "• All moving elements must follow cyclic paths so they return to the initial state.\n\n"
        "--- 3D ENVIRONMENT REQUIREMENTS ---\n"
        "• Build a full 3D world with depth, but keep it soft and easy on the eyes.\n"
        "• Keep the center area simple and unobtrusive for UI placement.\n"
        "• Place more detail in the horizon and side regions.\n"
        "• Maintain a pastel, painterly art style similar to casual mobile puzzle games.\n"
        "• No characters, text, or UI props.\n\n"
        "--- AUDIENCE TONE ---\n"
        "• Calm, nostalgic, light-hearted.\n"
        "• No harsh contrast, no fast-moving particles, no dramatic lighting.\n"
        "• Should feel welcoming and relaxing, not flashy or ‘kid-like.’\n\n"
        "--- OUTPUT GOAL ---\n"
        "Produce a high-quality 3D animated looping background video (1080p or 4K) with\n"
        "minimal motion, perfect loop (first = last frame), themed to {THEME}, suitable for\n"
        "a mature casual Bingo audience."""
    )
    return base.replace("{THEME}", theme or "")
